import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";
import Nav from "@/components/Navbarcomponents/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vakratund",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
         <Nav/>
        {children}
        </Providers>
      </body>
    </html>
  );
}
